### ISSUE TITLE
Could this library support with iOS platform?

### ISSUE THREAD

**Issue by ChhimChakriya** [maxim-puchkov/compress-pdf#8]
because I tried to implement it with iOS but it needs to call “Quartz” which called component “QuartzFilter” to use which is not available on IOS

**Comment by maxim-puchkov** [comment]
Hello! 

Unfortunately this code will not be able to run on iOS because of its dependency on the Apple's Quartz framework which is only available on macOS: https://developer.apple.com/documentation/quartz. 

It was actually the original idea of this project to create a mobile iOS application which would be able to scan & compress PDF documents. However, it was not possible due to this dependency. So I decided to create this project for macOS only and run it via command-line.

Maxim
